name: hyp3-isce2
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - numpy
  - pip
  - isce2=2.6.4
  - shapely
  - pyproj
  - jinja2
  - gdal
  - libcurl>=8.17.0 # https://github.com/ASFHyP3/hyp3-isce2/issues/390
  - burst2safe>=1.4.5
  - hyp3lib>=4,<5
  - s1_orbits
  - lxml
  - requests
  # For packaging, and testing
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - pytest-mock
  - pip:
    - -r requirements-static.txt
