name: hyp3-isce2
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - numpy
  - pip
  - isce2>=2.6.3
  - dem_stitcher>=2.5.8
  - rasterio
  - shapely
  - jinja2
  - asf_search>=6.4.0
  - gdal
  - opencv
  - burst2safe
  # For packaging, and testing
  - ruff
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - pytest-mock
  # For running
  - hyp3lib>=3,<4
  - s1_orbits
