name: Test and build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  call-pytest-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-pytest.yml@v0.9.0
    with:
      local_package_name: hyp3_isce2
      python_versions: >-
        ["3.9", "3.10"]

  call-version-info-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-version-info.yml@v0.9.0

  call-docker-ghcr-workflow:
    needs: call-version-info-workflow
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-docker-ghcr.yml@v0.9.0
    with:
      version_tag: ${{ needs.call-version-info-workflow.outputs.version_tag }}
      release_branch: main
      develop_branch: develop
      user: tools-bot
    secrets:
      USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
